variables:
  CI_DESIGNATED_BRANCH: prplos

include:
  - remote: https://gitlab.com/prpl-foundation/prplOS/prplos/-/raw/prplos/.gitlab/sdk.yml

generate:
  extends: .generate SDK package build jobs
  variables:
    CI_SDK_TARGETS: |
      intel_mips-xrx500
      ath79-generic-19.07.7
      mvebu-cortexa9
      ipq40xx-generic
    CI_SDK_BUILD_PACKAGES: |
      acl-manager
      amx-fcgi
      amxb-inspect
      amx-cli
      amxo-cg
      amxrt
      bbf
      bbfd
      cthulhu
      deviceinfo-manager
      dhcpv4-manager
      dhcpv6s-manager
      ethernet-manager
      firewall4
      gmap-mibs-common
      gmap-mod-ethernet-dev
      gmap-mod-name-selector
      gmap-mod-self
      gmap-server
      ip-manager
      libamxa
      libamxb
      libamxc
      libamxd
      libamxj
      libamxm
      libamxo
      libamxp
      libamxs
      libamxt
      libdhcpoptions
      libfwinterface
      libfwrules
      libgmap-client
      libnetmodel
      libsahtrace
      libtrace
      luci-mod-simple
      luci-theme-prpl
      moca-manager
      mod-amxb-ubus
      mod-ba-cli
      mod-dm-cli
      mod-dmext
      mod-dmproxy
      mod-dmstats
      mod-netmodel
      mod-pcm-svc
      mod-sahtrace
      mod-sahtrace
      mod-vlan-ioctl
      mod-vlan-uci
      multisettings
      netdev-plugin
      netmodel
      netmodel-dhcpv4
      netmodel-dhcpv6
      netmodel-ethernet
      netmodel-ip
      obuspa
      odl-generator
      owsd
      pcm-manager
      routing-manager
      time-manager
      tr181-bridging
      tr181-device
      tr181-dhcpv4client
      tr181-dhcpv6client
      tr181-firewall
      tr181-qos
      tr181-routeradvertisement
      tr181-usermanagement
      ucode
      ucwmp
      udrone
      uriparser
      wan-autosensing
      wan-manager

build:
  extends: .execute SDK package build jobs

.build prplmesh with SDK:
  tags:
    - firmware-builder
  extends: .build feed with SDK
  variables:
    CI_SDK_BUILD_PACKAGES: prplmesh

build prplmesh with intel_mips-xrx500 SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplos/prplos/$CI_DESIGNATED_BRANCH/sdk-intel_mips-xrx500:latest
    CI_SDK_INSTALL_FEEDS: base packages luci routing feed_intel

build prplmesh with ipq40xx-generic SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplos/prplos/$CI_DESIGNATED_BRANCH/sdk-ipq40xx-generic:latest

build prplmesh with mvebu-cortexa9 SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplos/prplos/$CI_DESIGNATED_BRANCH/sdk-mvebu-cortexa9:latest

build prplmesh with ath79-generic OpenWrt SDK:
  extends: .build feed with OpenWrt SDK
  tags:
    - firmware-builder
  variables:
    CI_SDK_IMAGE: openwrtorg/sdk:ath79-generic-19.07.7
    CI_SDK_BUILD_PACKAGES: prplmesh
