include:
  - remote: https://gitlab.com/prpl-foundation/prplwrt/prplwrt/-/raw/prplwrt/.gitlab/sdk.yml

generate:
  extends: .generate SDK package build jobs
  variables:
    CI_SDK_TARGETS: |
      intel_mips-xrx500
      ath79-generic-19.07.7
      mvebu-cortexa9
      ipq40xx-generic
    CI_SDK_BUILD_PACKAGES: |
      bbf
      bbfd
      firewall4
      libtrace
      luci-mod-simple
      luci-theme-prpl
      obuspa
      owsd
      ucode
      ucwmp
      udrone

build:
  extends: .execute SDK package build jobs

.build prplmesh with SDK:
  tags:
    - firmware-builder
  extends: .build feed with SDK
  variables:
    CI_SDK_BUILD_PACKAGES: prplmesh

build prplmesh with intel_mips-xrx500 SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplwrt/prplwrt/sdk-intel_mips-xrx500:latest
    CI_SDK_INSTALL_FEEDS: base packages luci routing feed_intel

build prplmesh with ath79-generic SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplwrt/prplwrt/sdk-ath79-generic:latest
    CI_SDK_BUILD_CONFIG_EXTRA: +PACKAGE_prplmesh-nl80211

build prplmesh with ipq40xx-generic SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplwrt/prplwrt/sdk-ipq40xx-generic:latest
    CI_SDK_BUILD_CONFIG_EXTRA: +PACKAGE_prplmesh-nl80211

build prplmesh with mvebu-cortexa9 SDK:
  extends: .build prplmesh with SDK
  variables:
    CI_SDK_IMAGE: registry.gitlab.com/prpl-foundation/prplwrt/prplwrt/sdk-mvebu-cortexa9:latest
    CI_SDK_BUILD_CONFIG_EXTRA: +PACKAGE_prplmesh-nl80211

build prplmesh with ath79-generic OpenWrt SDK:
  extends: .build feed with OpenWrt SDK
  tags:
    - firmware-builder
  variables:
    CI_SDK_IMAGE: openwrtorg/sdk:ath79-generic-19.07.7
    CI_SDK_BUILD_PACKAGES: prplmesh
    CI_SDK_BUILD_CONFIG_EXTRA: +PACKAGE_prplmesh-nl80211
