#!/usr/bin/env lua

local function restart()
        return os.execute("/etc/init.d/prplmesh restart >/dev/null 2>&1")
end

if arg[1] == "list" then
        print('{"restart":{}}')
elseif arg[1] == "call" then
        if restart() == 0 then result = "OK"
        else result = "FAIL"
        end
        print('{"result": "' .. result .. '"}')
        os.exit(0)
end
