#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

SERVICE=prplmesh

cron_job_command="*/5 * * * * /usr/sbin/morse-check-prplmesh.sh"
cron_job_script="/usr/sbin/morse-check-prplmesh.sh"

stop_agent_monitor() {
        if_exists=$(crontab -l | grep "$cron_job_script" | wc -l)
        if [ $if_exists -ne 0 ]; then
            # If it exists, remove it
            (crontab -l | grep -v "$cron_job_script") | crontab -
            logger "prplMesh Cron job removed successfully"
        fi
}

stop_service() {
        stop_agent_monitor
        /opt/prplmesh/scripts/prplmesh.init stop
}

start_agent_monitor() {
        #Check if the cron job already exists
        if_exists=$(crontab -l | grep "$cron_job_script" | wc -l)

        if [ $if_exists -eq 0 ]; then
            # If it doesn't exist, add it
            (crontab -l ; echo "$cron_job_command") | crontab -
            logger "prplMesh Cron job added successfully"
        else
            logger "prplMesh Cron job already exists"
        fi

}

start_service() {
        if [ "$(uci get prplmesh.config.enable 2>/dev/null)" = "1" ]; then
                start_agent_monitor
                procd_open_instance
                procd_set_param command /opt/prplmesh/scripts/prplmesh.init start
                procd_set_param stdout 1
                procd_set_param stderr 1
                procd_close_instance
        fi
}

reload_service() {
        stop
        # prplMesh doesn't like coming back up straight away
        # if the network configuration is changing under it.
        ( sleep 5; start ) &
}


service_triggers() {
       procd_add_reload_trigger "prplmesh" "network" "wireless"
}
