#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

PRPL_SERVICE="prplmesh"
PRPL_MGR_INSTANCE="prpl-mgr"

stop_service() {
    /opt/prplmesh/scripts/prplmesh.init stop
}

start_service() {
    [ "$(uci get prplmesh.config.enable 2>/dev/null)" = "1" ] || return 0

    # prplmesh prplmesh.init daemonises, procd won't supervise it correctly
    procd_open_instance "$PRPL_SERVICE"
    procd_set_param command /opt/prplmesh/scripts/prplmesh.init start
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    procd_open_instance "$PRPL_MGR_INSTANCE"
    procd_set_param command /usr/sbin/prpl-mgr
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

reload_service() {
    stop
    ( sleep 5; start ) &
}

service_triggers() {
    procd_add_reload_trigger "prplmesh" "network" "wireless"
}
